MODDICORE-276 Create function to populate an Authority Source file ID
folio-org/data-import-processing-core pull request #226
Opened 2022-07-27 20:12 UTC by maryna-steshenko

## Purpose
Create function to populate an Authority Source file ID.
[MODDICORE-276](https://issues.folio.org/browse/MODDICORE-276)

## Approach
- Schema for Authority Source File added
- SET_AUTHORITY_SOURCE_FILE_ID function implemented
- Tests for SET_AUTHORITY_SOURCE_FILE_ID function added

2022-07-29 09:48 UTC, psmagin requested changes

2022-07-29 09:48 UTC, psmagin commented on src/main/java/org/folio/processing/mapping/defaultmapper/processor/functions/NormalizationFunction.java
> +    Pattern p = Pattern.compile("[a-zA-Z]+");
We can't be sure that prefixes will be only alphabetical and not alphanumerical.

2022-07-29 09:48 UTC, psmagin commented on src/main/java/org/folio/processing/mapping/defaultmapper/processor/functions/NormalizationFunction.java
> +  }
This method is not searching for prefixes but also for substrings in the middle or end. For example for string `1234nmst123` it will find `nmst`

2022-07-29 09:48 UTC, psmagin commented on src/main/java/org/folio/processing/mapping/defaultmapper/processor/functions/NormalizationFunction.java
> +    }
I think that the best solution for this is to find the longest substring-prefix. A possible solution is to have a map sorted by a key length that starts with the longest with key = code and value = id and then iterate this map until we found a prefix that fits a condition value.startsWith(code)

2022-08-02 10:59 UTC, viacheslavkol approved these changes

2022-08-02 11:48 UTC, oliinyko approved these changes

2022-08-03 05:52 UTC, merged